# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: mixed-line-ending

repos:
-   repo: github.com/pre-commit/mirrors-csslint
    rev: master
    hooks:
    -   id: csslint

repos:
-   repo: github.com/Lucas-C/pre-commit-hooks-java
    rev: master
    hooks:
    -   id: validate-html

repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: clang-format
        exclude: (^attic|^build|^doc)
    -   id: cpplint
        exclude: (^attic|^build|^doc)
    -   id: cppcheck
        exclude: (^attic|^build|^doc)
        args: [--language=c++,--inline-suppr]
